LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(  '',include('books.urls')),
]

LMS/books/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import *

app_name= "books"

urlpatterns = [
    path('',studentView.as_view(),name="studentView"),
    path('Add-book/',Add_book.as_view(),name="Add_book"),
    path('update-book/', update_book.as_view(),name = "update_book"),
    path('update-book/<int:id>', update_book.as_view(), name = "update_book" ),
    path('delete-book/<int:id>', delete_book.as_view(), name = "delete_book" ),
    
]

LMS/books/models.py
from email.policy import default
from django.db import models

class Book(models.Model):
    book_no = models.IntegerField(default=0)
    name= models.CharField(max_length=200, blank=True, null=True)
    Author_name = models.CharField(max_length=200, blank=True, null=True)
    def __str__(self): 
        return self.name

LMS/books/forms.py
from email.policy import default
from django import forms
from books.models import Book


class BookForm(forms.ModelForm):
    book_no = forms.IntegerField()
    name = forms.CharField(max_length=200)
    Author_name = forms.CharField(max_length=200)
    
    class Meta: 
      model = Book
      fields = '__all__' 

LMS/books/views.py
from django.shortcuts import render
from django.views.generic.base import View
from books.forms import BookForm
from books.models import *
from django.shortcuts import redirect
from django.urls import reverse


class studentView (View):
    def get(self, request):
        booklist = Book.objects.all()
        print(booklist)
        return render(request, "books/booklist.html", context= {'booklist': booklist})
    
    

class Add_book(View):
    def get(self, request):
        booklist= Book.objects.all()
        print(booklist)
        return render(request, "books/Add_book.html", context= {'booklist': booklist})
        
    def post(self, request):
       
            Mybook = BookForm(request.POST) 
            if Mybook.is_valid():
                Mybook.save()
                return redirect(reverse('books:studentView'))
            else:
                print(Mybook.errors)
            return render(request, "books/Add_book.html", context= { })


class update_book(View):
    def get(self, request,id):
        book_obj = Book.objects.get(pk=id)
        booklist= Book.objects.all()
        return render(request, "books/update_book.html", context= {'book_obj' : book_obj, 'booklist' : booklist})
    
    def post(self, request,id):
        obj = Book.objects.get(pk=id)
        Mybook = BookForm(request.POST, instance=obj)
        if Mybook.is_valid():
            Mybook.save()
            return redirect(reverse('books:studentView'))
          
        else:    
            print(Mybook.errors)
        return redirect(reverse('Users:userView'))

class delete_book(View):
    def get(self, request, id):
        obj = Book.objects.get(pk=id)
        obj.delete()
        return redirect(reverse('books:studentView'))
    

LMS/templates/books/Add_book.html
{% extends 'content/base.html' %}
{% load static %}


{% block content %}

<h1> Add Books details </h1>

<form name = "form" action = "{% url "books:Add_book" %}" 
         method = "POST" >{% csrf_token %}

    <div class="form-group">
        <label for="exampleInputPassword1"> Book Number </label>
        <input type="number" name= "book_no" class="form-control" id="exampleInputPassword1" placeholder="Enter Book Number">
    </div>

    <div class="form-group">
      <label for="exampleInputEmail1">Book name</label>
      <input type="name" name= "name" class="form-control" id="exampleInputEmail1" placeholder="Enter Book name">
      </div>
    
    <div class="form-group">
      <label for="exampleInputPassword1"> Author Name </label>
      <input type="name" name= "Author_name" class="form-control" id="exampleInputPassword1" placeholder="Enter Author name">
    </div>

    
     <button type="submit" class="btn btn-primary">Submit</button>
  </form>
 {% endblock %}

 {% block javaScript %}
 
 
 {% endblock %}

LMS/templates/books/booklist.html
{% extends 'content/base.html' %}
{% load static %}



{% block content %}


<h1> Books list </h1> <a href = "{% url 'books:Add_book'%}" type="button" class="btn btn-primary"> Add Book </a>  
<table id = "mytable" class = "datatable" > 
  

<thead>
<tr>
    <th> Serial number </th> 
    <th> Book Number </th>
    <th> Book Name </th>
    <th> Author Name </th>
    <th> Action </th>
  </tr>
</thead>
<tbody>
    {% for Book in booklist %}
    <tr>
      <td>{{forloop.counter}} </td>
      <td> {{Book.book_no}} </td>
      <td> {{Book.name}} </td>
      <td> {{Book.Author_name}} </td>
      <td> <a  href = "{% url 'books:update_book' id=Book.id %}" type="button" class="btn btn-primary">Update </a>   
        <a  href = "{% url 'books:delete_book' id=Book.id %}" type="button" class="btn btn-primary"> Delete </a> </td> 
    </tr>
    {% endfor %}
  </tbody>
  </table> 



 {% endblock %}

 {% block javaScript %}
 
 
 {% endblock %}

{% comment %} 
 href = "{% url 'books:update_book' id=Book.id %}"
 href = "{% url 'books:delete_student' id=Book.id %}" {% endcomment %}

LMS/templates/books/update_book.html
from django.contrib import admin
from students.models import *



{% extends 'content/base.html' %}
{% load static %}



{% block content %}

<h1> Update Book details </h1>

<form name = "form"  
         method = "POST" >{% csrf_token %}

    <div class="form-group">
        <label for="exampleInputPassword1">Book Number  </label>
        <input type="number" name = "book_no" class="form-control" id="book_no" value ="{{Book_obj.book_no}}" 
    </div>

    <div class="form-group">
      <label for="exampleInputEmail1">Book name</label>
      <input type="name" name = "name" class="form-control" id="name" value ="{{Book_obj.name}}" 
      </div>
    
    <div class="form-group">
      <label for="exampleInputPassword1">Author Name </label>
      <input type="name" name = "Author_name"class="form-control" id="Author_name" value ="{{Book_obj.Author_name}}" 
    </div>
    

    <button <a type="submit" class="btn btn-primary">Update</a></button>
  </form>








 {% endblock %}

 {% block javaScript %}
 
 
 {% endblock %}


 {% comment %} action = "{% url "books:update_book" id=Book_obj.id  %}"  {% endcomment %}

LMS/templates/content/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard - NiceAdmin Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css'%} " rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.2.0
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  {% include 'content/header.html' %}

  <!-- ======= Sidebar ======= -->
  {% include 'content/sidebar.html' %}

  <main id="main" class="main">

    {% block content %}

    {% endblock %}

    

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'content/footer.html' %}

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>

  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %} "></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.min.js' %} "></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %} "></script>

  {% block javaScript %}
  {% endblock %}

</body>

</html>

LMS/templates/content/footer.html
<!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
      &copy; Copyright <strong><span>NiceAdmin</span></strong>. All Rights Reserved
    </div>
    <div class="credits">
      <!-- All the links in the footer should remain intact. -->
      <!-- You can delete the links only if you purchased the pro version. -->
      <!-- Licensing information: https://bootstrapmade.com/license/ -->
      <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/ -->
      Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
    </div>
  </footer><!-- End Footer -->

LMS/templates/content/header.html
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="index.html" class="logo d-flex align-items-center">
        <img src="assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">NiceAdmin</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-bell"></i>
            <span class="badge bg-primary badge-number">4</span>
          </a><!-- End Notification Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow notifications">
            <li class="dropdown-header">
              You have 4 new notifications
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-exclamation-circle text-warning"></i>
              <div>
                <h4>Lorem Ipsum</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>30 min. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-x-circle text-danger"></i>
              <div>
                <h4>Atque rerum nesciunt</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>1 hr. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-check-circle text-success"></i>
              <div>
                <h4>Sit rerum fuga</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>2 hrs. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="notification-item">
              <i class="bi bi-info-circle text-primary"></i>
              <div>
                <h4>Dicta reprehenderit</h4>
                <p>Quae dolorem earum veritatis oditseno</p>
                <p>4 hrs. ago</p>
              </div>
            </li>

            <li>
              <hr class="dropdown-divider">
            </li>
            <li class="dropdown-footer">
              <a href="#">Show all notifications</a>
            </li>

          </ul><!-- End Notification Dropdown Items -->

        </li><!-- End Notification Nav -->

        <li class="nav-item dropdown">

          <a class="nav-link nav-icon" href="#" data-bs-toggle="dropdown">
            <i class="bi bi-chat-left-text"></i>
            <span class="badge bg-success badge-number">3</span>
          </a><!-- End Messages Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow messages">
            <li class="dropdown-header">
              You have 3 new messages
              <a href="#"><span class="badge rounded-pill bg-primary p-2 ms-2">View all</span></a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="assets/img/messages-1.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>Maria Hudson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>4 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="assets/img/messages-2.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>Anna Nelson</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>6 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="message-item">
              <a href="#">
                <img src="assets/img/messages-3.jpg" alt="" class="rounded-circle">
                <div>
                  <h4>David Muldon</h4>
                  <p>Velit asperiores et ducimus soluta repudiandae labore officia est ut...</p>
                  <p>8 hrs. ago</p>
                </div>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li class="dropdown-footer">
              <a href="#">Show all messages</a>
            </li>

          </ul><!-- End Messages Dropdown Items -->

        </li><!-- End Messages Nav -->

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>Kevin Anderson</h6>
              <span>Web Designer</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-person"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-gear"></i>
                <span>Account Settings</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span>Need Help?</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-box-arrow-right"></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

LMS/templates/content/sidebar.html
  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
        <a class="nav-link " href= "{% url 'books:studentView' %}">
          <i class="bi bi-grid"></i>
          <span>book list </span>
        </a>
      </li><!-- End Dashboard Nav -->

      

      

      
    </ul>

  </aside><!-- End Sidebar-->